INSERT INTO players(fName, lName, positionType) VALUES('John', 'Smith', 'Attacker');
INSERT INTO players (fName, lName, positionType) VALUES ('Michael', 'Johnson', 'midfielder');
INSERT INTO players (fName, lName, positionType) VALUES ('David', 'Brown', 'defender');
INSERT INTO players (fName, lName, positionType) VALUES ('Robert', 'Taylor', 'goalkeeper');
INSERT INTO players (fName, lName, positionType) VALUES ('James', 'Anderson', 'attacker');
INSERT INTO players (fName, lName, positionType) VALUES ('William', 'Jones', 'midfielder');
INSERT INTO players (fName, lName, positionType) VALUES ('Joseph', 'Davis', 'defender');
INSERT INTO players (fName, lName, positionType) VALUES ('Thomas', 'Wilson', 'goalkeeper');
INSERT INTO players (fName, lName, positionType) VALUES ('Charles', 'Moore', 'attacker');
INSERT INTO players (fName, lName, positionType) VALUES ('Daniel', 'Taylor', 'midfielder');
INSERT INTO players (fName, lName, positionType) VALUES ('Matthew', 'White', 'defender');
INSERT INTO players (fName, lName, positionType) VALUES ('Christopher', 'Martin', 'goalkeeper');
INSERT INTO players (fName, lName, positionType) VALUES ('Andrew', 'Thompson', 'attacker');
INSERT INTO players (fName, lName, positionType) VALUES ('Anthony', 'Garcia', 'midfielder');
INSERT INTO players (fName, lName, positionType) VALUES ('Mark', 'Martinez', 'defender');