INSERT INTO teams(teamName) VALUES
 ('Queens Park Rangers'),
 ('Leicester City'),
 ('Aston Villa'),
 ('Swansea City'),
 ('Stoke City'),
 ('Southampton'),
 ('West Bromwich Albion'),
 ('Crystal Palace'),
 ('Tottenham Hotspur'),
 ('Manchester United'),
 ('Manchester City'),
 ('Newcastle United'),
 ('Chelsea'),
 ('Burnley'),
 ('West Ham United'),
 ('Arsenal'),
 ('Hull City'),
 ('Everton'),
 ('Liverpool'),
 ('Sunderland')